CREATE DATABASE IF NOT EXISTS test;
USE test;
CREATE TABLE IF NOT EXISTS test1 (ID TEXT NOT NULL,PRIMARY KEY (ID(255)),Password TEXT(255));
INSERT INTO test1 (ID,Password)
VALUES ("wow","wow2");

SELECT * FROM test1;